name: cursorhackathon-app
services:
  - name: frontend
    image:
      registry_type: DOCKER_HUB
      registry: balajimurugesan2016
      repository: frontend
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: API_BACKEND_URL
        value: "http://placeholder:8085"
      - key: PROBABILITY_SERVICE_URL
        value: "http://placeholder:8097"
